#!/usr/bin/env python3
"""Generate 30 Akari (Light Up) puzzles, emit AKPuzzles.mc.

Cell encoding (matches the Monkey C runtime):
    0       white cell  (player can place bulb here)
    1       wall, no number (no adjacency constraint)
    2..6    wall with number k = (cell - 2),  k in 0..4
                → exactly k bulbs must be adjacent (4-way)

Solution encoding: parallel flat list bulbs[n*n] ∈ {0,1}.

Generation strategy:
    1. Pick a wall density and number-density for the target diff.
    2. Sprinkle walls uniformly across the grid (LCG seed).
    3. Greedily place bulbs so every white cell is lit and no two
       bulbs attack each other.  If greedy fails, retry with a
       different seed (we typically converge in <10 tries).
    4. Number every wall with its adjacent-bulb count (numbering
       *all* walls makes the puzzle effectively uniquely
       solvable for the small grid sizes we use here).

Output: AKPuzzles.mc with EASY (6×6) and HARD (7×7) buckets.
"""

import random

DIRS = [(-1, 0), (1, 0), (0, -1), (0, 1)]


def is_wall(v):
    return v != 0


def compute_lit(cells, bulbs, n):
    lit = [False] * (n * n)
    for i in range(n * n):
        if not bulbs[i]:
            continue
        r, c = i // n, i % n
        lit[i] = True
        for dr, dc in DIRS:
            rr, cc = r + dr, c + dc
            while 0 <= rr < n and 0 <= cc < n and not is_wall(cells[rr * n + cc]):
                lit[rr * n + cc] = True
                rr += dr
                cc += dc
    return lit


def can_place_bulb(cells, bulbs, n, idx):
    r, c = idx // n, idx % n
    if is_wall(cells[idx]):
        return False
    if bulbs[idx]:
        return False
    for dr, dc in DIRS:
        rr, cc = r + dr, c + dc
        while 0 <= rr < n and 0 <= cc < n and not is_wall(cells[rr * n + cc]):
            if bulbs[rr * n + cc]:
                return False
            rr += dr
            cc += dc
    return True


def adjacent_bulbs(bulbs, idx, n):
    r, c = idx // n, idx % n
    k = 0
    for dr, dc in DIRS:
        rr, cc = r + dr, c + dc
        if 0 <= rr < n and 0 <= cc < n and bulbs[rr * n + cc]:
            k += 1
    return k


def try_generate(n, wall_density, rng):
    cells = [0] * (n * n)
    for i in range(n * n):
        if rng.random() < wall_density:
            cells[i] = 1

    bulbs = [0] * (n * n)
    # Repeatedly pick a random unlit white cell that can still host a
    # bulb (no existing bulb sees it).  If no candidate, place a bulb
    # on any unlit white cell — usually that means the cell isn't
    # reachable from anywhere, so we add a bulb directly.
    for safety in range(n * n * 4):
        lit = compute_lit(cells, bulbs, n)
        unlit = [
            i for i in range(n * n)
            if cells[i] == 0 and not lit[i] and not bulbs[i]
        ]
        if not unlit:
            break
        candidates = [i for i in unlit if can_place_bulb(cells, bulbs, n, i)]
        if not candidates:
            return None
        bulbs[rng.choice(candidates)] = 1
    else:
        return None

    # Sanity: every white cell lit, no bulb attacks another.
    lit = compute_lit(cells, bulbs, n)
    for i in range(n * n):
        if cells[i] == 0 and not lit[i]:
            return None
    for i in range(n * n):
        if bulbs[i]:
            r, c = i // n, i % n
            for dr, dc in DIRS:
                rr, cc = r + dr, c + dc
                while 0 <= rr < n and 0 <= cc < n and not is_wall(cells[rr * n + cc]):
                    if bulbs[rr * n + cc]:
                        return None
                    rr += dr
                    cc += dc

    # Number every wall.
    for i in range(n * n):
        if cells[i] == 1:
            k = adjacent_bulbs(bulbs, i, n)
            cells[i] = 2 + k

    return cells, bulbs


def generate(n, wall_density, seed_base):
    """Try a few seeds until one converges."""
    for s in range(200):
        rng = random.Random(seed_base * 131 + s)
        out = try_generate(n, wall_density, rng)
        if out is not None:
            return out
    raise RuntimeError("Failed to generate %dx%d" % (n, n))


def fmt_list(xs):
    return "[" + ", ".join(str(x) for x in xs) + "]"


def emit(filename, easy, hard):
    lines = []
    lines.append("// AUTO-GENERATED by _gen_puzzles.py — DO NOT EDIT.")
    lines.append("// 30 Akari (Light Up) puzzles:")
    lines.append("//   EASY 6x6: %d puzzles" % len(easy))
    lines.append("//   HARD 7x7: %d puzzles" % len(hard))
    lines.append("")
    lines.append("class AKPuzzles {")
    for name, lst in [("EASY", easy), ("HARD", hard)]:
        lines.append("    static var %s = [" % name)
        for cells, bulbs in lst:
            n = int(len(cells) ** 0.5)
            lines.append(
                "        [%d, %s, %s]," % (n, fmt_list(cells), fmt_list(bulbs))
            )
        lines.append("    ];")
    lines.append("}")
    with open(filename, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    easy = []
    for i in range(15):
        # Wall density rises slightly with index for difficulty curve.
        wd = 0.20 + 0.012 * i
        easy.append(generate(6, wd, seed_base=1000 + i))
    hard = []
    for i in range(15):
        wd = 0.22 + 0.010 * i
        hard.append(generate(7, wd, seed_base=2000 + i))
    emit(
        "/Users/kkorolczuk/work/garmin/akari/source/AKPuzzles.mc",
        easy,
        hard,
    )
    print("emitted %d easy + %d hard" % (len(easy), len(hard)))
