#!/usr/bin/env python3
"""Generate 30 hand-designed Nonogram puzzles into NGPuzzles.mc.

Format emitted (flat-list-per-puzzle, easy to consume in Monkey C):

    static var EASY = [
        [5, sol_flat_25, rowClues_flat, rowOffs, colClues_flat, colOffs],
        ...
    ];

Where:
  n              = grid edge (5 or 6)
  sol_flat       = list of n*n ints (0/1)
  rowClues_flat  = concatenation of all row clue lists
  rowOffs        = n+1 prefix-sums into rowClues_flat
  colClues_flat  = same, for columns
  colOffs        = n+1 prefix-sums into colClues_flat
"""

PUZZLES_5 = [
    # 1. heart
    [" XX X",
     "XXXXX",
     "XXXXX",
     " XXX ",
     "  X  "],
    # 2. smile
    ["XX XX",
     "XX XX",
     "     ",
     "X   X",
     " XXX "],
    # 3. arrow up
    ["  X  ",
     " XXX ",
     "XXXXX",
     "  X  ",
     "  X  "],
    # 4. plus
    ["  X  ",
     "  X  ",
     "XXXXX",
     "  X  ",
     "  X  "],
    # 5. X mark
    ["X   X",
     " X X ",
     "  X  ",
     " X X ",
     "X   X"],
    # 6. house
    ["  X  ",
     " XXX ",
     "XXXXX",
     "X X X",
     "XXXXX"],
    # 7. fish
    ["  XX ",
     "XXXXX",
     "X X X",
     "XXXXX",
     "  XX "],
    # 8. tree
    ["  X  ",
     " XXX ",
     "XXXXX",
     " XXX ",
     "  X  "],
    # 9. boat
    ["  X  ",
     "  X  ",
     "  X  ",
     "XXXXX",
     " XXX "],
    # 10. diamond
    ["  X  ",
     " X X ",
     "X   X",
     " X X ",
     "  X  "],
    # 11. ring
    ["XXXXX",
     "X   X",
     "X   X",
     "X   X",
     "XXXXX"],
    # 12. eye
    [" XXX ",
     "XX XX",
     "X X X",
     "XX XX",
     " XXX "],
    # 13. arrow right
    ["  X  ",
     "   X ",
     "XXXXX",
     "   X ",
     "  X  "],
    # 14. ladder
    ["X   X",
     "XXXXX",
     "X   X",
     "XXXXX",
     "X   X"],
    # 15. bow tie
    ["X   X",
     "XX XX",
     " XXX ",
     "XX XX",
     "X   X"],
    # 16. star (small)
    ["  X  ",
     "X X X",
     " XXX ",
     "X X X",
     "  X  "],
    # 17. letter A
    ["  X  ",
     " X X ",
     "XXXXX",
     "X   X",
     "X   X"],
    # 18. letter H
    ["X   X",
     "X   X",
     "XXXXX",
     "X   X",
     "X   X"],
]

PUZZLES_6 = [
    # 1. big heart
    [" XX XX",
     "XXXXXX",
     "XXXXXX",
     " XXXX ",
     "  XX  ",
     "      "],
    # 2. mushroom
    ["  XX  ",
     " XXXX ",
     "XXXXXX",
     "X XX X",
     "  XX  ",
     "  XX  "],
    # 3. invader
    [" X  X ",
     "  XX  ",
     " XXXX ",
     "XX XX X"[0:6],
     "X    X",
     " X  X "],
    # 4. crown
    ["X X X ",
     "X X X ",
     "XXXXX ",
     "XXXXX ",
     "XXXXX ",
     "      "],
    # 5. cat face
    ["X    X",
     "XX  XX",
     "XXXXXX",
     "X XX X",
     "XXXXXX",
     " X  X "],
    # 6. ship
    ["   X  ",
     "   X  ",
     "  XXX ",
     "XXXXXX",
     " XXXX ",
     "      "],
    # 7. ladder big
    ["X    X",
     "XXXXXX",
     "X    X",
     "XXXXXX",
     "X    X",
     "XXXXXX"],
    # 8. arrow diag
    ["X     ",
     "XX    ",
     "XXX   ",
     "XXXX  ",
     "XXXXX ",
     "XXXXXX"],
    # 9. spiral-ish
    ["XXXXXX",
     "X    X",
     "X XX X",
     "X XX X",
     "X    X",
     "XXXXXX"],
    # 10. butterfly
    ["X    X",
     "XX  XX",
     "XXXXXX",
     "XXXXXX",
     "XX  XX",
     "X    X"],
    # 11. flower
    ["  XX  ",
     " XXXX ",
     "XXXXXX",
     "XXXXXX",
     " XXXX ",
     "  XX  "],
    # 12. anchor
    ["  XX  ",
     " X  X ",
     "  XX  ",
     "  XX  ",
     "X XX X",
     " XXXX "],
]


def to01(rows, n):
    out = []
    for r in rows:
        line = (r + " " * n)[:n]
        out.extend(1 if ch != ' ' else 0 for ch in line)
    return out


def clues_for_line(line):
    runs, cur = [], 0
    for v in line:
        if v:
            cur += 1
        else:
            if cur:
                runs.append(cur)
                cur = 0
    if cur:
        runs.append(cur)
    return runs if runs else [0]


def encode(rows, n):
    flat = to01(rows, n)
    # rows
    row_clues, row_offs = [], [0]
    for r in range(n):
        rc = clues_for_line(flat[r * n:(r + 1) * n])
        row_clues.extend(rc)
        row_offs.append(len(row_clues))
    # cols
    col_clues, col_offs = [], [0]
    for c in range(n):
        col = [flat[r * n + c] for r in range(n)]
        cc = clues_for_line(col)
        col_clues.extend(cc)
        col_offs.append(len(col_clues))
    return n, flat, row_clues, row_offs, col_clues, col_offs


def fmt_list(name, ll):
    return f"[{', '.join(str(x) for x in ll)}]"


def emit(filename, easy, hard):
    lines = []
    lines.append("// AUTO-GENERATED by _gen_puzzles.py — DO NOT EDIT by hand.")
    lines.append("// 30 hand-designed Nonogram puzzles:")
    lines.append(f"//   Easy 5x5: {len(easy)} puzzles")
    lines.append(f"//   Hard 6x6: {len(hard)} puzzles")
    lines.append("")
    lines.append("class NGPuzzles {")
    for name, lst in [("EASY", easy), ("HARD", hard)]:
        lines.append(f"    static var {name} = [")
        for rows in lst:
            n = len(rows[0]) if rows else 5
            n, flat, rc, ro, cc, co = encode(rows, n)
            lines.append(
                "        [" + str(n) + ", "
                + fmt_list("flat", flat) + ", "
                + fmt_list("rc", rc) + ", "
                + fmt_list("ro", ro) + ", "
                + fmt_list("cc", cc) + ", "
                + fmt_list("co", co) + "],"
            )
        lines.append("    ];")
    lines.append("}")
    with open(filename, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    emit("/Users/kkorolczuk/work/garmin/nonogram/source/NGPuzzles.mc",
         PUZZLES_5, PUZZLES_6)
    print(f"emitted {len(PUZZLES_5)} easy + {len(PUZZLES_6)} hard")
